spring:
  boot:
    admin:
      client:
        prefer-ip: true
      url: http://127.0.0.1:17601/app-admin
  sleuth:
    enabled: true
    scheduled:
      enabled: false
    async:
      enabled: false
      configurer:
        enabled: false
    integration:
      enabled: false
    zuul:
      enabled: false
    web:
      #接收的那些请求不会trace,注意是正则
      skip-pattern: /v2/api-docs.*|/api-docs.*|/error.*|/swagger.*|.*\.png|.*\.css|.*\.js|.*\.html|/favicon.ico|/hystrix.stream
      client:
        #发出去的那些请求不会trace,注意是以prefix开始的uri,中间用,分隔
        skip-uri-prefix: /app-admin
    sampler:
      #采样比率,1所有请求都trace,0.1百分之十的请求会trace
      percentage: 1
  zipkin:
    base-url: http://127.0.0.1:17601

logging:
  config: classpath:log4j2-test.xml

netty:
  boss:
    thread-count: 2
  worker:
    thread-count: 2
  tcp:
    port: 60000
  so:
    keepalive: true
    backlog: 100